const express = require("express");
const { ObjectId } = require("mongodb");

// Design render approval pipeline (Ori, 2026-07-20). The Design studio's two
// jobs: (1) show clients what we can do, (2) feed the formal Scope of Work.
// Every render a designer wants to keep is SUBMITTED here (status "pending"),
// then a designer reviews it for buildability and rough price and either
// approves ("render approval"), sends it back ("changes"), or rejects it.
// Only APPROVED renders appear in the client showcase and are attachable to a
// Scope of Work document — and every surface that shows one must carry the AI
// disclaimer below (a CSLB-licensed contractor must never present an AI render
// as a photograph or a promise of the finished product).
//
// Collection: designRenders. Mount: crmApp.use("/api/design", require("./designreview")(collection));

const AI_DISCLAIMER =
  "AI concept visualization — this image was generated by AI to communicate design intent. " +
  "The finished project may differ in materials, colors, dimensions, and details. " +
  "The work performed is defined solely by the written Scope of Work.";

const STATUSES = ["pending", "approved", "changes", "rejected"];
const FEASIBILITY = ["high", "medium", "low"];

function cleanString(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function cleanNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? Math.round(n) : 0;
}

function pickEnum(value, allowed, fallback) {
  const raw = cleanString(value).toLowerCase();
  return allowed.includes(raw) ? raw : fallback;
}

// Only ever store our own /uploads paths (the studio uploads both images there
// first) — never arbitrary URLs, which would let the review/showcase pages
// hot-link external content.
function cleanUploadUrl(value) {
  const raw = cleanString(value);
  return raw.startsWith("/uploads/") ? raw : "";
}

function mapRow(row) {
  return { ...row, id: row._id.toString(), _id: undefined };
}

function normalizeSubmission(input) {
  const body = input && typeof input === "object" ? input : {};
  const projectName = cleanString(body.projectName) || "Design Studio";
  return {
    projectId: cleanString(body.projectId) || "design-studio",
    projectName,
    title: cleanString(body.title).slice(0, 120),
    roomType: cleanString(body.roomType).slice(0, 60),
    style: cleanString(body.style).slice(0, 60),
    mode: pickEnum(body.mode, ["redecorate", "remodel", "staging", "exterior"], "redecorate"),
    beforeUrl: cleanUploadUrl(body.beforeUrl),
    afterUrl: cleanUploadUrl(body.afterUrl),
    altUrls: (Array.isArray(body.altUrls) ? body.altUrls : []).map(cleanUploadUrl).filter(Boolean).slice(0, 6),
    renderPrompt: cleanString(body.renderPrompt).slice(0, 4000),
    submittedBy: cleanString(body.submittedBy).slice(0, 80),
    status: "pending",
    review: null,
    showcase: false,
    updatedAt: new Date().toISOString()
  };
}

module.exports = (collection) => {
  const router = express.Router();
  router.use(express.json({ limit: "1mb" }));
  const noDb = { error: "MongoDB is not configured. Set MONGODB_URI to enable server persistence." };

  async function renders() {
    return collection("designRenders");
  }

  async function photoLog() {
    return collection("photoLog");
  }

  // The disclaimer is served, not hardcoded client-side, so every consumer
  // (studio, review queue, showcase, SOW doc) prints the same current wording.
  router.get("/disclaimer", (_req, res) => {
    res.json({ disclaimer: AI_DISCLAIMER });
  });

  // List renders, newest first. ?status=pending|approved|changes|rejected,
  // ?projectId= both optional. ?showcase=1 narrows to client-showcase picks.
  router.get("/renders", async (req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    const filter = {};
    const status = pickEnum(req.query.status, STATUSES, "");
    if (status) filter.status = status;
    if (cleanString(req.query.projectId)) filter.projectId = cleanString(req.query.projectId);
    if (String(req.query.showcase) === "1") { filter.status = "approved"; filter.showcase = true; }
    const rows = await coll.find(filter).sort({ createdAt: -1 }).limit(500).toArray();
    res.json(rows.map(mapRow));
  });

  // Status counts — drives the review-queue badge on the Design tabs.
  router.get("/renders/summary", async (_req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    const rows = await coll.aggregate([{ $group: { _id: "$status", n: { $sum: 1 } } }]).toArray();
    const counts = { pending: 0, approved: 0, changes: 0, rejected: 0 };
    for (const row of rows) if (counts[row._id] !== undefined) counts[row._id] = row.n;
    const showcase = await coll.countDocuments({ status: "approved", showcase: true });
    res.json({ ...counts, showcase });
  });

  // Submit a render for designer review (from the Design studio save flow).
  router.post("/renders", async (req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    const doc = { ...normalizeSubmission(req.body), createdAt: new Date().toISOString() };
    if (!doc.beforeUrl || !doc.afterUrl) {
      return res.status(400).json({ error: "beforeUrl and afterUrl (uploaded /uploads paths) are required." });
    }
    const result = await coll.insertOne(doc);
    res.status(201).json({ ...doc, id: result.insertedId.toString() });
  });

  // Designer decision. decision: approve | changes | reject. Approve requires a
  // feasibility read; price range is the designer's rough build number for this
  // concept (used as guidance on the SOW, not a quote).
  router.post("/renders/:id/review", async (req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    let _id;
    try { _id = new ObjectId(req.params.id); } catch { return res.status(400).json({ error: "Bad id." }); }
    const record = await coll.findOne({ _id });
    if (!record) return res.status(404).json({ error: "Render not found." });
    // A decided render is final: re-reviewing an approved render would insert a
    // duplicate photo-feed entry and wholesale-overwrite the designer's saved
    // feasibility/price (review loop 1 finding). Delete + resubmit to redo.
    if (record.status === "approved" || record.status === "rejected") {
      return res.status(409).json({ error: `This render is already ${record.status}. Delete it and resubmit to review again.` });
    }

    const body = req.body || {};
    const decision = pickEnum(body.decision, ["approve", "changes", "reject"], "");
    if (!decision) return res.status(400).json({ error: "decision must be approve, changes, or reject." });
    const feasibility = pickEnum(body.feasibility, FEASIBILITY, "");
    if (decision === "approve" && !feasibility) {
      return res.status(400).json({ error: "Approval requires a feasibility rating (high/medium/low)." });
    }
    const priceLow = cleanNumber(body.priceLow);
    const priceHigh = Math.max(cleanNumber(body.priceHigh), priceLow);

    const status = decision === "approve" ? "approved" : decision === "reject" ? "rejected" : "changes";
    const review = {
      feasibility,
      priceLow,
      priceHigh,
      notes: cleanString(body.notes).slice(0, 2000),
      reviewedBy: cleanString(body.reviewedBy).slice(0, 80) || "Designer",
      reviewedAt: new Date().toISOString()
    };
    const showcase = status === "approved" ? body.showcase !== false : false;
    await coll.updateOne({ _id }, { $set: { status, review, showcase, updatedAt: new Date().toISOString() } });

    // Approved concepts also land on the project photo feed (the studio used to
    // post there directly; now the feed only ever shows designer-approved work).
    if (status === "approved") {
      const feed = await photoLog();
      if (feed) {
        await feed.insertOne({
          projectId: record.projectId,
          projectName: record.projectName,
          photoUrl: "",
          caption: record.title || (record.renderPrompt || "Design concept").split(".")[0].slice(0, 120),
          tags: ["design", record.mode, "approved"].filter(Boolean),
          phase: "finish",
          takenAt: new Date().toISOString(),
          beforeAfterPair: { beforeUrl: record.beforeUrl, afterUrl: record.afterUrl },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        });
      }
    }
    const updated = await coll.findOne({ _id });
    res.json(mapRow(updated));
  });

  // Edit showcase flag / title after the fact (approved renders only for showcase).
  router.put("/renders/:id", async (req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    let _id;
    try { _id = new ObjectId(req.params.id); } catch { return res.status(400).json({ error: "Bad id." }); }
    const record = await coll.findOne({ _id });
    if (!record) return res.status(404).json({ error: "Render not found." });
    const patch = { updatedAt: new Date().toISOString() };
    if (req.body.title !== undefined) patch.title = cleanString(req.body.title).slice(0, 120);
    if (req.body.roomType !== undefined) patch.roomType = cleanString(req.body.roomType).slice(0, 60);
    if (req.body.showcase !== undefined) patch.showcase = record.status === "approved" && !!req.body.showcase;
    await coll.updateOne({ _id }, { $set: patch });
    res.json(mapRow(await coll.findOne({ _id })));
  });

  router.delete("/renders/:id", async (req, res) => {
    const coll = await renders();
    if (!coll) return res.status(503).json(noDb);
    let _id;
    try { _id = new ObjectId(req.params.id); } catch { return res.status(400).json({ error: "Bad id." }); }
    await coll.deleteOne({ _id });
    res.status(204).end();
  });

  return router;
};

module.exports.AI_DISCLAIMER = AI_DISCLAIMER;
